<?php

/**
 * Implements hook_theme().
 */
function fm_image_slider_theme() {
  return array(
    'fm_image_slider_nivo_formatter' => array(
      'variables' => array(
        'pictures' => array(),
        'image_style' => '',
        'thumb_style' => '',
      ),
      'file' => 'fm_image_slider.theme.inc',
    ),
    'fm_image_slider_slides_formatter' => array(
      'variables' => array(
        'pictures' => array(),
        'image_style' => '',
        'thumb_style' => '',
      ),
      'file' => 'fm_image_slider.theme.inc',
    ),
  );
}

function fm_image_slider_field_formatter_info() {
	return array(
    'image_slider' => array(
      'label' => t('FM Main Image Slider'),
      'field types' => array('node_reference'),
	    'settings' => array('product_image_style' => '', 'product_thumb_style' => ''),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function fm_image_slider_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  
  $image_styles = image_style_options(FALSE);
  $element['product_image_style'] = array(
    '#title' => t('Product image style'),
    '#type' => 'select',
    '#default_value' => $settings['product_image_style'],
    '#empty_option' => t('None (original image)'),
    '#options' => $image_styles,
  );
  
  $element['product_thumb_style'] = array(
    '#title' => t('Product Thumb style'),
    '#type' => 'select',
    '#default_value' => $settings['product_thumb_style'],
    '#empty_option' => t('None (original image)'),
    '#options' => $image_styles,
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function fm_image_slider_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  
  $summary = array();

  $image_styles = image_style_options(FALSE);
  // Unset possible 'No defined styles' option.
  unset($image_styles['']);
  // Styles could be lost because of enabled/disabled modules that defines
  // their styles in code.
  if (isset($image_styles[$settings['product_image_style']])) {
    $summary[] = t('Product image style: @style', array('@style' => $image_styles[$settings['product_image_style']]));
  }
  else {
    $summary[] = t('Product image style: Original image');
  }
  
  if (isset($image_styles[$settings['product_thumb_style']])) {
    $summary[] = t('Product thumb style: @style', array('@style' => $image_styles[$settings['product_thumb_style']]));
  }
  else {
    $summary[] = t('Product thumb style: Original image');
  }
  return implode('<br />', $summary);
}

function fm_image_slider_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
	
	$element = array();
	$settings = $display['settings'];
	switch ($display['type']) {
		case 'image_slider':
			$element = array(
        '#theme' => 'fm_image_slider_slides_formatter',
        '#pictures' => $items,
			  '#image_style' => $display['settings']['product_image_style'],
			  '#thumb_style' => $display['settings']['product_thumb_style']
      );
			break;
	}
	return $element;
}

