<?php

/**
 * Implements hook_menu().
 */
function fm_commerce_express_checkout_menu() {
	
	$items['express-checkout'] = array(
    'page callback' => 'fm_commerce_express_checkout_page',
	  'access arguments' => array('view deals'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

function fm_commerce_express_form_alter(&$form, &$form_state, $form_id) {
	var_dump('test');
	if($form_id == 'commerce_checkout_form') {
	  $form['#theme'] = 'fm_commerce_express_checkout';
	}
}


function fm_commerce_express_checkout_theme($variables)
{
    return array
    (
        'fm_commerce_express_checkout' => array(
            'render element' => 'form',
            'template' => 'fm_commerce_express_checkout'
        ),
    );
}
