<?php

function fm_deals_notify_menu() {
	
	$items['deals/notify/%'] = array(
    'title' => t('Fadmashion Notify'),
	  'page arguments' => array(2), 
    'page callback' => 'fm_deals_notify_add_reminder',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

function fm_deals_notify_add_reminder($nid) {
	global $user;
	
	$exists = fm_deals_notify_entry_exists($nid, $uid);
	
	if(!$exists) {
	  $id = db_insert('fm_deals_notify')
      ->fields(array(
        'nid' => $nid,
        'uid' => $user->uid,
        'timestamp' => REQUEST_TIME,
        'sent' => 0
      ))
    ->execute();
    
    $message = fm_deals_notify_return_message();
	}
	else {
		$message = t('You are already on the list.');
	}
	
	drupal_json_output(array('messsage' => $message));
	exit;
}

function fm_deals_notify_entry_exists($nid, $uid) {
	$result = db_query('SELECT * FROM {fm_deals_notify} WHERE nid = :nid AND uid = :uid', array(':nid' => $nid, 'uid' => $uid));
  
	$obj = $result->fetchObject();
  if($obj) {
  	return true;
  }
  else {
  	return false;
  }
}

function fm_deals_notify_get_button() {
	
}

function fm_deals_notify_return_message() {
	
	$message = t('Wise Choice. Expect a reminder e-mail from us 15 minutes before this deal starts');
	return $message;
}