<?php

//require 'facebook-php-sdk/src/facebook.php';

function fm_social_facebook_init() {
	drupal_add_js(drupal_get_path('module', 'fm_social_facebook') . '/fm_social_facebook.js');
	
}

function fm_social_facebook_fb_user($op, $data, &$return) {
	if($op == FB_USER_OP_POST_USER) {
		$account = $data['account'];
		db_query("UPDATE {users} SET status=1 WHERE uid = :uid", array(':uid' => $account->uid));
		_user_mail_notify('register_no_approval_required', $account);
		
		$form_state = null;
		fm_social_favorite_authenticated_form_submit(null, $form_state);
		
		
		//fm_commerce_cart_add_credits_to_cart(); 
		
		//rules_invoke_all('user_insert', $account);
	} else if($op == FB_USER_OP_POST_EXTERNAL_LOGIN) {
		$form_state = null;
		fm_social_favorite_authenticated_form_submit(null, $form_state);
		
		//fm_commerce_cart_add_credits_to_cart(); 
	}
}

