<?php

/**
 * Implements hook_menu().
 */
function fm_deals_menu() {
	
	$items['deals'] = array(
    'page callback' => 'fm_deals_page',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/fadmashion/deals'] = array(
    'title' => t('Deals Listing'), 
    'description' => t('Listing of all Upcoming Deals'),
    'page callback' => 'fm_deals_list',
    'access arguments' => array('administer deals list'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'fm_deals.admin.inc',
  );
  
  return $items;
}

/**
 * Implements hook_permission().
 */
function fm_deals_permission() {
  return array(
    'administer deals list' => array(
      'title' => t('View Deals List'),
    ),
  );
}





/**
 * Implements hook_theme().
 */
function fm_deals_theme() {
	return array(
    'fm_deals_product_details' => array(
	     'variables' => array(
         'title' => '',
	       'description' => '',
	       'product' => NULL,
	       'store' => NULL
	    )
    ),
    'fm_deals_preview' => array(
	     'variables' => array('node' => NULL, 'store' => NULL, 'image' => ''),
       'template' => 'fm_deals_preview'
    ),
  );
}

/**
 * Implements hook_commerce_currency_info().
 */
function fm_deals_commerce_currency_info() {
  return array(
    'USD' => array(
      'format_callback' => 'fm_deals_format_price'
    ),
   );
}

/**
 * Implements hook_form_alter().
 */
function fm_deals_form_alter(&$form, $form_state, $form_id) {
	$posi = strpos($form_id, 'commerce_cart_add_to_cart_form');  
  if (is_numeric($posi)){
		$form['submit']['#value'] = "Purchase Now";
		$form['#submit'][] = 'fm_deals_cart_submit';
  }
}

//REDIRECTS Deals page TO STEP 2 after submit
function fm_deals_cart_submit ($form, &$form_state) {
   //code here
   $form_state['redirect'] = 'checkout'; 
}

function fm_deals_format_price($amount, $currency, $object) {
	
  // Separate the negative symbol from the number itself.
  if ($amount < 0) {
    $negative = TRUE;
    $price = abs($amount);
  }
  else {
    $negative = FALSE;
  }
  
  // FM Custom - make 0 decimal.
  $price = number_format(commerce_currency_round($amount, $currency), 0, $currency['decimal_separator'], $currency['thousands_separator']);

  // Establish the replacement values to format this price for its currency.
  $replacements = array(
    '@code_before' => $currency['code_placement'] == 'before' ? $currency['code'] : '',
    '@symbol_before' => $currency['symbol_placement'] == 'before' ? $currency['symbol'] : '',
    '@price' => $price,
    '@symbol_after' => $currency['symbol_placement'] == 'after' ? $currency['symbol'] : '',
    '@code_after' => $currency['code_placement'] == 'after' ? $currency['code'] : '',
    '@negative' => $negative ? '-' : '',
  );

  return trim(t('@code_before @negative@symbol_before@price @symbol_after @code_after', $replacements));
	
}

/*
 * implementation of hook_preprocess_node()
 */

function fm_deals_preprocess_node(&$vars) {
	//Add  Variables to fm_group_buying node tempalte
	if($vars['node']->type == 'fm_group_buying') {
	  $product = fm_deals_get_product($vars['node']);
		$store = fm_deals_get_store($product);  
		
		$vars['store'] = $store;
		
		//Set Time Until for Countdown
		$details= fm_deals_group_details($vars);
		
	  if(isset($vars['field_sale_price']) && isset($vars['elements']['product:commerce_price'])) {
		  //Calculate Percentage for product sale
		  $sale_price = field_get_items('node', $vars['node'], 'field_sale_price');
		  $sale_price = $sale_price[0]['amount'];
 		
		  $original_price = field_get_items('commerce_product', $product, 'commerce_price');
		  $original_price = $original_price[0]['amount'];
		
      $raw_value = round(1 - ($sale_price/$original_price), 2);
      $value = ($raw_value * 100). '%';
      $vars['sale_percentage'] = $value;
	  }
    
	  //Create quicktabs for Product Details
	  $description = field_get_items('node', $vars['node'], 'field_description_global');
	  $description = $description[0]['value'];
	  if(!isset($description)) {
	  	//If description is not set on Node than use the description of the first product listed
	  	$description = field_get_items('commerce_product', $product, 'field_description');
	    $description = $description[0]['value'];
	  }
	  $title = $vars['node']->title;
	  
    $quicktabs = new stdClass();
    $tabs['product_details'] = array(
            'title' => t('Details'),
            'type' => 'freetext',
            'text' => theme('fm_deals_product_details', 
                             array('store' => $store, 'title' => $title, 'description' => $description, 'product' => $product) ),
    );
    $tabs['product_shipping'] = array(
            'title' => t('Shipping & Returns'),
            'type' => 'freetext',
            'text' => t('Free Text2'),
    );
   /*$tabs['product_returns'] = array(
            'title' => t('Returns'),
            'type' => 'freetext',
            'text' => t('Free Text2'),
    );*/
    $quicktabs->tabs = $tabs;
    $quicktabs->table = 'quicktabs';
    $quicktabs->ajax= '0';
    $quicktabs->style = 'default';
    $quicktabs->type = 'Normal';
    $quicktabs->default_tab = 'product_details';
    $quicktabs->hide_empty_tabs = '0';
    $quicktabs->machine_name = 'fm_product_details';
    
    $qt = quicktabs_render($quicktabs);
    $vars['detail_tabs'] = $qt;
	}
}

function fm_deals_get_product($node) {
    $wrapper = entity_metadata_wrapper('node', $node);
	  
	  $field = field_info_field('field_product_reference');
	  if ($field['cardinality'] == 1) {
      $product = $wrapper->field_product_reference->value();
	  }
    else {
      $product = $wrapper->field_product_reference->get(0)->value();
    }
    return $product;
}

function fm_deals_get_store($product) {
	$store_ref = field_get_items('commerce_product', $product, 'field_store_reference');
	$store_id = $store_ref[0]['store_id'];
	
	$stores = fm_commerce_store_load_multiple(array($store_id));
	return $stores[$store_id];
}

function theme_fm_deals_product_details($vars) {
	$title = $vars['title'];
  $description = $vars['description'];
  $product = $vars['product'];
  $store = $vars['store'];
  
  $output = '<h1 class="itemName">' . $title . '</h1>';
  $output .= '<h2>' . l($store->name, 'test') . '</h2>';
  $output .= '<p>' . $description . '</p>';
  return $output;
}



function fm_deals_page($nid = '') {
	if(empty($nid)) {
		$default = fm_deals_get_default_deal();
		$nid = $default['nid'];
	}
	
	if(!empty($nid)) {
		drupal_goto('node/' . $nid);
	}
	else {
		drupal_set_message('There was an error in the system.  Please contact us so we can quickly resolve', 'error+');
	}
	
}

//Get the deal that needs to be active right now.  MUST return some node value.
function fm_deals_get_default_deal() {
	
	$request_time = date('Y-m-d H:i:s', REQUEST_TIME);
	
	$query = new EntityFieldQuery();
	//First try to get the deal that is happening right now.
  $entities = $query->entityCondition('entity_type', 'node')
                    ->entityCondition('bundle', 'fm_group_buying')
                    ->propertyCondition('status', 1)
                    ->fieldCondition('field_start_time', 'value', $request_time, '<')
                    ->fieldCondition('field_start_time', 'value2', $request_time, '>')
                    ->fieldOrderBy('field_start_time', 'value', 'ASC')
                    ->execute();
  if(isset($entities['node'])) {
    $first_node = array_shift($entities['node']);
    return array('nid' => $first_node->nid, 'active' => true);
  }
  else {
  	//If there is no active deal than get the next upcoming deal
  	$query = new EntityFieldQuery();
  	$entities = $query->entityCondition('entity_type', 'node')
                    ->entityCondition('bundle', 'fm_group_buying')
                    ->propertyCondition('status', 1)
                    ->fieldCondition('field_start_time', 'value', $request_time, '>')
                    ->fieldOrderBy('field_start_time', 'value', 'ASC')
                    ->execute();
                    var_dump($entities);
    if(isset($entities['node'])) {
      $first_node = array_shift($entities['node']);
      return array('nid' => $first_node->nid, 'active' => false);
    }
  }
}

function fm_deals_group_details(&$vars) {
	$node = $vars['node'];
	
	$start_time = $node->field_start_time['und'][0]['value'];
	$end_time = $node->field_start_time['und'][0]['value2'];
	
	$unixStartTime = strtotime($start_time);
	$unixEndTime = strtotime($end_time);
	
	//If start time is GREATER THAN NOW than disabled.
	if(REQUEST_TIME < $unixStartTime) {
		$timerDetails = '<div style="text-align: center; padding-top: 8px;">Deal Starts <span class="countdown">' . date("D, F d @ g:ia", $unixStartTime) . '</span></div>';
		$untilTime = $start_time;
		
		$purchaseDetails = '<div class="button"><a href="#">Remind Me</a></div>';
	}
	elseif (REQUEST_TIME > $unixStartTime  && REQUEST_TIME < $unixEndTime) {
		$timerDetails = '<div class="col1">Items Left: <span>35</span></div>
               <div class="col2">Time  Left: <span class="countdown">00:00</span></div>';
		$untilTime = $end_time;
		
		$purchaseDetails = render($vars['content']['field_product_reference']);
	  //If start time is LESS THAN NOW this is ACTIVE
	  jquery_countdown_add(".countdown", array("until" =>  date("F d, Y g:i a", strtotime($untilTime)), 'format' => 'DHMS', "layout" => '{mnn}:{snn}'));
  
	} 
	else {
		$timerDetails = '<div style="text-align: center; padding-top: 8px;">Deal Has Ended</div>';
		$purchaseDetails = '<div class="button"><a href="#">Notify Me</a></div>';
	}
	
	$vars['groupDetails'] = $timerDetails;
	$vars['purchaseDetails'] = $purchaseDetails;
}



