<?php

/*
 * FUNCTIONALITY:
 * Newsletters are generated Via an Admin form and saved as a special
 * node Content type designated just for newsletters.  
 * 
 * Once the newsletter is saved, than copy and paste generated code to preferred
 * mail service to send out.
 * 
 * ARCHITECTURE:
 

abstract class fm_newsletters {
	
	private $node; 
	
	private $title;
	private $body;
	
	private $vars;
	
	
	function __construct() {
		$node = new stdObject();
		$title = '';
		$body = '';
	}
	
	public function setTitle($new_title) {
		$title = $new_title;
	}
	
	public function save() {
		
	}
	
	abstract protected function setVars();
	abstract protected function generateBody();
}*/


/*
 * Implements hook_node_insert()
 */
function fm_newsletters_node_presave($node) {
	if($node->type == 'fm_newsletters_deals') {
	   $node = fm_newsletters_deals_generate_code($node);
	}
	
}

function fm_newsletters_theme() {
	 return array(
     'fm_newsletters_deals' => array(
	     'template' => 'fm_newsletters_deals',
	     'variables' => array(
         'featured' => '',
	       'more' => '',
	    )
    ),
    'fm_newsletters_deals_featured' => array (
       'template' => 'fm_newsletters_deals_featured',
       'variables' => array(
         'node' => NULL,
         'time' => NULL,
      )
    ),
    'fm_newsletters_deals_more' => array (
       'template' => 'fm_newsletters_deals_more',
       'variables' => array(
         'nodes' => NULL,
         'times' => NULL
      )
    ),
    'fm_newsletters_deals_more_item' => array (
       'template' => 'fm_newsletters_deals_more_item',
       'variables' => array(
         'node' => NULL,
          'time' => NULL
      )
    )
  );
}

function fm_newsletters_image_path() {
	return 'http://www.fadmashion.com/' . drupal_get_path('theme', 'fadmashion_commerce') . '/images/';
}


function fm_newsletters_deals_generate_url($product, $image_style = 'fm_preview_block_thumb') {

 $images = field_get_items('commerce_product', $product, 'field_product_images');
    
	$first_image = node_load($images[0]['nid']);
  $first_image = field_get_items('node', $first_image, 'field_product_image');
  $first_image = $first_image[0];
  
  $image = array(
      'path' => $first_image['uri'],
      'alt' => $first_image['alt'],
      'title' => $first_image['title'],
      'attributes' => array('class' => 'itemThumb'),
      'style_name' => $image_style
  );
  
  return theme('image_style', $image);
   
}

function fm_newsletters_deals_generate_code($node) {
	$collection = field_get_items('node', $node, 'field_news_deals_collection');
	$nids = array();
	$deal_times = array();
	foreach($collection as $item) {
	  $a_field_collection_item = entity_load('field_collection_item', array($item['value']) );
	  foreach ($a_field_collection_item as $a_field_collection_item_object ) {
	  	//var_dump($a_field_collection_item_object);
	  	$deal_nid = field_get_items('field_collection_item', $a_field_collection_item_object, 'field_newsletters_deals');
      $node_nid = $deal_nid[0]['nid'];
      $nids[] = $node_nid;
      
      $deal_time = field_get_items('field_collection_item', $a_field_collection_item_object, 'field_newsletters_time');
      $deal_time = strtotime($deal_time[0]['value']);
      fm_deals_insert_directly($node_nid, $deal_time);
      $deal_times[] = $deal_time;
    }
	}
	
	$first_nid = array_shift($nids);
	$featured_node = node_load($first_nid);
	$featured_time = array_shift();
	
	
	$more_deals = array();
	foreach($nids as $nid) {
		$more_deals[] = node_load($nid);
	}
	
	$featured = theme('fm_newsletters_deals_featured', array('node' => $featured_node, 'time' => $featured_time));
	$more = theme('fm_newsletters_deals_more', array('nodes' => $more_deals, 'times' => $deal_times) );
	$output = theme('fm_newsletters_deals', array('featured' => $featured, 'more' => $more));
	
	$node->body[$node->language][0]['value']   = $output;
	$node->body[$node->language][0]['format']  = 'full_html'; 
	
	return $node;
}




?>