<?php
define('COLLECTION_VIEWER_PAGER', 10);
/**
 * Implements hook_menu().
 */
function fm_shop_menu() {
	
	$items['shop'] = array(
    'page callback' => 'fm_shop_page',
	  'access arguments' => array('view deals'),
    'type' => MENU_CALLBACK,
  );
  
  $items['shop/ajax/%'] = array(
    'page callback' => 'fm_shop_page_ajax',
	  'access arguments' => array('view deals'), 
    'page arguments' => array(2, 3),
    'type' => MENU_CALLBACK,
  );
  
  
  return $items;
}

function fm_shop_init() {
	drupal_add_js(drupal_get_path('module', 'fm_shop') . '/fm_shop.js');
}

/**
 * Implements hook_theme().
 */
function fm_shop_theme() {
  return array(
    'fm_shop_page' => array(
	     'variables' => array('filters' => '', 'content' => ''),
	    'template' => 'fm_shop_page'
    ),
    'fm_shop_page_panel' => array(
	     'variables' => array('shop' => NULL, 'products' => NULL, 'filter_group' => ''),
       'template' => 'fm_shop_page_panel'
    ),
    'fm_shop_page_panel_thumb' => array(
	     'variables' => array('product' => NULL, 'shop' => NULL,  'height' => 446, 'width' => 315),
       'template' => 'fm_shop_page_panel_thumb'
    ),
    'fm_shop_page_collection_slider' => array(
	     'variables' => array('products' => NULL, 'argument' => array(), 'pager' => 0),
       'template' => 'fm_shop_page_collection_slider'
    ),
    
  );
}

function fm_shop_page() {

	drupal_add_js(path_to_theme() . '/js/jquery.capSlide.js');
  drupal_add_css(path_to_theme() . '/css/captions.css');
  drupal_add_js(path_to_theme() . '/js/jquery.ad-gallery.js');
  drupal_add_css(path_to_theme() . '/css/jquery.ad-gallery.css');
  drupal_add_js(path_to_theme() . '/js/jquery-textFill.js');
    
  $filters = fm_shop_page_filters();
  //$content = fm_shop_page_all_panels($filters);
  
  return theme('fm_shop_page', array('filters' => $filters, 'content' => $content));
}

function fm_shop_page_ajax($type) {
	
	$type = 'all';
	if(isset($_GET['store_id']) && $_GET['store_id'] != '' ) {
		$store_id = $_GET['store_id'];
		$type = 'shop';
	} 
	
   if(isset($_GET['term']) && $_GET['term'] != '' ) {
		$term_name = $_GET['term'];
		$type = 'term';
   }
	
	$page = $_GET['page'];
	
	switch($type) {
		case 'all':
		  $filters = fm_shop_page_filters();
		  $content = '<div id="all">';
      $panels = fm_shop_page_all_panels($filters);
      
      foreach($panels as $panels_group) {
     	   foreach($panels_group as $panel) {
       	 	 $content .= $panel;
     	   }
       } 
      $content .= '</div>';
      //WE only want a 3 step loading process (for now)
      if($page < 2) {
      	$html = 'Loading More...';
      	$html .= '<br><img src="' . pp() .'confirm-ajax-loader.gif">';
      	$content .= '<div id="loading_more" style="display:none">';
        $content .= l($html, 'shop/ajax/all', array('html' => true, 'query' => array('page' => ($page + 1)), 'attributes' => array('rel' => 'next',  ) ));
        $content .= '</div>';
         
    	  $content .= '<script type="text/javascript">jQuery(function() {jQuery.autopager({content: ".designerPanel", appendTo: ".col2 #all", load: autoPagerLoad, start: autoPagerStart });});</script>';
      }
    	    
	    break;
		case 'shop':
			$shop = fm_commerce_store_load($store_id);
			$products = fm_commerce_store_get_products($shop);
			
			$content =  fm_shop_collection_viewer('store', $shop, $products);
			
	    break;
		case 'term':
			$term = taxonomy_get_term_by_name($term_name);
			$term = array_shift($term);
			$values = fm_shop_products_by_taxonomy($term);
			$products = $values['products'];
			
			//Calculate oager
			if(!isset($_GET['page'])) {
				$page = 1;
			} else {
				$page = $_GET['page'] + 1;
			}
			
			if($page * COLLECTION_VIEWER_PAGER > $values['total']) {
				$pager = 0;
			} else {
				$pager = $page;
			}
			
			$content =  fm_shop_collection_viewer('term', $term, $products, $pager) ;
	    break;
			
	}
	
	
	$node_content = '';
	foreach($products as $product) {
	 $node = fm_commerce_get_display_node($product);
	 $node_content .= render(node_view($node));
	}
	
	$content .= '<div class="product_content">';
	$content .= $node_content;
	$content .= '</div>';
	
	print $content;
	exit();
}

function fm_shop_collection_viewer($type, $var, $products, $pager = 0) {

	$content = '';
	switch($type) {
		case 'store':
			$shop = $var;
			$content = '<div id = "collection_store_' . $shop->store_id . '">';
			$content .= theme('fm_shop_page_collection_slider', array('products' => $products, 'argument' => array('store_id' => $shop->store_id)));
			$content .= '</div>';
			
			break;
		case 'term':
			$term = $var;
			$content = '<div id = "collection_term_' . $term->name . '">';
			$content .= theme('fm_shop_page_collection_slider', array('products' => $products, 'pager' => $pager,  'argument' => array('term' => $term->name)));
			$content .= '</div>';
			break;
	}
	
	return $content;
	
}


function fm_shop_page_filters() {
	$filters = array();
	
	//Get Featured List 
	$filters['product_type']['title'] = '';
	$filters['product_type']['links'] = array();
	$filters['product_type']['arg'] = 'term'; 
	$vocab = taxonomy_vocabulary_machine_name_load('product_types');
	$terms = taxonomy_get_tree($vocab->vid);
  foreach ($terms as  $term) {
    $filters['product_type']['links'][$term->name] = check_plain($term->name);
  }
	
	
	
//Get Featured List 
	$filters['featured']['title'] = t('Featured');
	$filters['featured']['links'] = array();
	$filters['featured']['arg'] = 'store_id';
	
	
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'fm_commerce_store');
	$query->propertyOrderBy('weight', 'asc');
	$query->propertyCondition('status', 1);
	$query->fieldCondition('field_featured', 'value', 1);
	$result = $query->execute();
	
  $matches = array();
  foreach ($result['fm_commerce_store'] as $store_id => $store) {
    $shop = fm_commerce_store_load($store_id);
    $filters['featured']['links'][$shop->store_id] = check_plain($shop->name);
  }
  
	//Get Designer List
	$filters['designers']['title'] = t('Designers');
	$filters['designers']['links'] = array();
	$filters['designers']['arg'] = 'store_id';
	
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'fm_commerce_store');
	$query->propertyOrderBy('weight', 'asc');
	$query->propertyCondition('status', 1);
	$result = $query->execute();

  $matches = array();
  foreach ($result['fm_commerce_store'] as $store_id => $store) {
    $shop = fm_commerce_store_load($store_id);
    $shop_name = check_plain($shop->name);
    if(!in_array($shop_name, $filters['featured']['links'])) {
      $filters['designers']['links'][$shop->store_id] = $shop_name;
    }
  }
  
  return $filters;
}

function fm_shop_page_all_panels($filters) {
	$content = array();
	$page = $_GET['page'];
  
	$total = 0;
	foreach($filters as $filter_group) {
		if(!empty($filter_group['title'])) {
	    $total += count($filter_group['links']);
		}
	}
	$half = ceil($total/2);
	
	switch($page) {
		case 0:
			$start = 0;
			$end = 3;
			break;
		case 1:
			$start = 3;
			$end = $half+2;
			break;
		case 2:
			$start = $half+2;
			$end = $total;
			break;
	}
	
  foreach($filters as $filter_group) {
  	$title = $filter_group['title'];
  	if(!empty($title)) {
  	  $content[$title] = array();
      foreach($filter_group['links'] as $id => $link) {
      	if($i >= $start && $i < $end) {
    	    $shop = fm_commerce_store_load($id);
    	    $products = fm_commerce_store_get_products($shop, true);
     
      	  if(!empty($products)) {
      	    $designerPanel = theme('fm_shop_page_panel', array('shop' => $shop, 'products' => $products, 'filter_group' => $title));
    	      $content[$title][] = $designerPanel;
      	    
    	    }
    	  }
    	  $i++;
      }
  	}
  } 
  
  return $content;
}

function fm_shop_products_by_taxonomy($term) {
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'commerce_product')
	   ->entityCondition('bundle', 'fm_fashion_product')
    ->fieldCondition('field_product_type_top', 'tid', $term->tid) //replace field_food_menu with field_TAXONOMY_NAME and 2 with taxonomy ID (or use this code in a loop for many terms)
    ->pager(COLLECTION_VIEWER_PAGER)
    ->propertyCondition('status', 1)
    ->propertyOrderBy('created', 'DESC');
    
  $products = $query->execute();
  
	$products_ret = array();
	if(isset($products['commerce_product'])) {
    foreach($products['commerce_product'] as $product_id => $product) {
      $products_ret[$product_id] = commerce_product_load($product_id);
	  }
	}
	
	return array('products' => $products_ret, 'total' => $query->pager['total']);
	
}