<?php
function fm_home_menu() {
	
	$items['home'] = array(
    'page callback' => 'fm_home_page',
	  'access arguments' => array('view deals'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function fm_home_init() {
	drupal_add_js(drupal_get_path('module', 'fm_home') . '/fm_home.js');
	//drupal_add_js(drupal_get_path('theme', 'v15_fadmashion_commerce').'/js/jquery.cycle.all.js');
}

function fm_home_theme() {
	return array(
    'fm_home_category_panel' => array(
	     'variables' => array('term' => '', 'title' => '', 'image' => ''),
	    'template' => 'fm_home_category_panel'
    ),
    
    'fm_home_style_panel' => array(
	     'variables' => array('term' => '', 'title' => '', 'images' => array()),
	    'template' => 'fm_home_style_panel'
    ),
    
    'fm_home_promo_panel' => array(
	    'template' => 'fm_home_promo_panel'
    ),
    'fm_home_browse_panel' => array(
	    'template' => 'fm_home_browse_panel'
    ),
    
  );
}

function fm_home_page() {
	$content = '';
	$tids = array();
	
	//First Column
	$content .= '<div class="column">';
	$content .= fm_home_page_panel('Chelsea Class');
	$content .= fm_home_page_panel('Bold as BedStuy');
	$content .= '</div>';
	
	$content .= '<div class="column">';
	$content .= theme('fm_home_promo_panel');
	$content .= fm_home_page_panel('Upper West Side Lux');
	$content .= theme('fm_home_browse_panel');
	$content .= '</div>';
	
	$content .= '<div class="column">';
	$content .= fm_home_page_panel('Bedford Avenue Bedlam');
	$content .= fm_home_page_panel('West Village Vibe');
	$content .= '</div>';
	
	
	/* Small Panels */
	$content .= '<div class="smallPanels">';
	
	//Jewelry, Dresses, Tops, Bags, Shoes
	$terms = array('Jewelry', 'Dresses', 'Tops', 'Bags', 'Shoes');
	foreach($terms as $name) {
		$term = taxonomy_get_term_by_name($name);
		if(!empty($term)) {
			$term = array_shift($term);
		  $title = fm_home_get_category_label($term);
		  $images = fm_home_get_images($term, 'fm_home_small');
		  $image = array_shift($images);
      $content .= theme('fm_home_category_panel', array('term' => $term, 'title' =>$title, 'image' => $image));
		}  
	
	}
	$content .= '</div>';
	
	
	return $content;
	
}

function fm_home_get_images($term, $image_style) {
	$category_images = field_get_items('taxonomy_term', $term, 'field_category_home_image');
	$images = array();
	if($category_images) {
		foreach($category_images as $category_image) {
      $image_node = node_load($category_image['nid']);
      $image = field_get_items('node', $image_node, 'field_product_image');
      
      $images[] = image_style_url($image_style, $image[0]['uri']);
	  }
	  
    return $images;
	}
}

function fm_home_get_random_images($term, $image_style) {
	
 if($term->vocabulary_machine_name == 'product_types') {
		$field = 'field_product_type_top';
	} else {
		$field = 'field_product_trend';
	}
	
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'commerce_product')
	   ->entityCondition('bundle', 'fm_fashion_product')
    ->fieldCondition($field, 'tid', $term->tid) //replace field_food_menu with field_TAXONOMY_NAME and 2 with taxonomy ID (or use this code in a loop for many terms)
    ->propertyCondition('status', 1)
    ->propertyOrderBy('created', 'DESC');
    
  $products = $query->execute();
  
  
	$products_ret = array();
	if(isset($products['commerce_product'])) {
    foreach($products['commerce_product'] as $product_id => $product) {
      $products_ret[$product_id] = commerce_product_load($product_id);
	  }
	}
	
	shuffle($products_ret);
	
	$images_ret = array();
	
	for($i = 0; $i < 5; $i++) {
		$product = array_shift($products_ret);
		$images = field_get_items('commerce_product', $product, 'field_product_images');
	   //Get First Image
     $image_node = node_load($images[0]['nid']);
     $image = field_get_items('node', $image_node, 'field_product_image');
     $image = $image[0];
     $image = image_style_url($image_style, $image['uri']);
     $images_ret[] = $image;
	}
     
	return $images_ret;
  
  
}


function fm_home_page_panel($term_name) {
	
	$term = taxonomy_get_term_by_name($term_name);
	if(!empty($term)) {
			$term = array_shift($term);
		  $title = fm_home_get_category_label($term);
		  $images = fm_home_get_random_images($term, 'fm_home_big');
      $content = theme('fm_home_style_panel', array('term' => $term, 'title' =>$title, 'images' => $images));
	} 
	return $content;
}


function fm_home_get_category_label($term) {
  $category_label = field_get_items('taxonomy_term', $term, 'field_category_home_label');
  $title = '';
  
  if($category_label) {
      $category_label = $category_label[0];
			  
      $label = array(
       'path' => $category_label['uri'],
       'alt' => $category_label['alt'],
       'title' => $category_label['title'],
       'attributes' => array('class' => 'title'),
      );
   
      $title =  theme('image', $label);
  }
    
  return $title;
}