<?php
function fm_home_menu() {
	
	$items['home'] = array(
    'page callback' => 'fm_home_page',
	  'access arguments' => array('view deals'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function fm_home_init() {
	drupal_add_js(drupal_get_path('module', 'fm_home') . '/fm_home.js');
}

function fm_home_theme() {
	return array(
    'fm_home_category_panel' => array(
	     'variables' => array('term' => '', 'title' => '', 'image' => ''),
	    'template' => 'fm_home_category_panel'
    ),
    
    'fm_home_style_panel' => array(
	     'variables' => array('term' => '', 'title' => '', 'images' => array()),
	    'template' => 'fm_home_style_panel'
    ),
    
    'fm_home_promo_panel' => array(
	    'template' => 'fm_home_promo_panel'
    ),
    'fm_home_browse_panel' => array(
	    'template' => 'fm_home_browse_panel'
    ),
    
  );
}

function fm_home_page() {
	$content = '';
	$tids = array();
	
	//First Column
	$content .= '<div class="column">';
	$content .= fm_home_page_panel('Chelsea Class');
	$content .= fm_home_page_panel('Bold as BedStuy');
	$content .= '</div>';
	
	$content .= '<div class="column">';
	$content .= theme('fm_home_promo_panel');
	$content .= fm_home_page_panel('Upper West Side Lux');
	$content .= theme('fm_home_browse_panel');
	$content .= '</div>';
	
	$content .= '<div class="column">';
	$content .= fm_home_page_panel('Bedford Avenue Bedlam');
	$content .= fm_home_page_panel('West Village Vibe');
	$content .= '</div>';
	
	
	/* Small Panels */
	$content .= '<div class="smallPanels">';
	
	//Jewelry, Dresses, Tops, Bags, Shoes
	$terms = array('Jewelry', 'Dresses', 'Tops', 'Bags', 'Shoes');
	foreach($terms as $name) {
		$term = taxonomy_get_term_by_name($name);
		if(!empty($term)) {
			$term = array_shift($term);
		  $title = fm_home_get_category_label($term);
		  $images = fm_home_get_images($term, 'fm_home_small');
		  $image = array_shift($images);
      $content .= theme('fm_home_category_panel', array('term' => $term, 'title' =>$title, 'image' => $image));
		}  
	
	}
	$content .= '</div>';
	
	
	return $content;
	
}

function fm_home_get_images($term, $image_style) {
	$category_image = field_get_items('taxonomy_term', $term, 'field_category_home_image');
	$images = array();
	if($category_image) {
      $category_image = $category_image[0];
      $image_node = node_load($category_image['nid']);
      $image = field_get_items('node', $image_node, 'field_product_image');
      
      $images = array(image_style_url($image_style, $image[0]['uri']));
      return $images;
	}
}


function fm_home_page_panel($term_name) {
	
	$term = taxonomy_get_term_by_name($term_name);
	if(!empty($term)) {
			$term = array_shift($term);
		  $title = fm_home_get_category_label($term);
		  $images = fm_home_get_images($term, 'fm_home_big');
      $content = theme('fm_home_style_panel', array('term' => $term, 'title' =>$title, 'images' => $images));
	} 
	return $content;
}


function fm_home_get_category_label($term) {
  $category_label = field_get_items('taxonomy_term', $term, 'field_category_home_label');
  $title = '';
  
  if($category_label) {
      $category_label = $category_label[0];
			  
      $label = array(
       'path' => $category_label['uri'],
       'alt' => $category_label['alt'],
       'title' => $category_label['title'],
       'attributes' => array('class' => 'title'),
      );
   
      $title =  theme('image', $label);
  }
    
  return $title;
}