<?php
/*
 * implement hook_theme
 */
function fm_commerce_emails_theme() {
	return array(
	  'fm_commerce_emails_user_order_confirmation' => array(
	    'variables' => array('order' => NULL,  'product' => NULL, 'shop' => NULL, 'thumb' => NULL),
      'template' => 'fm_commerce_emails_user_order_confirmation'
     ),
    'fm_commerce_emails_store_order_confirmation' => array(
	    'variables' => array('order' => NULL,  'product' => NULL, 'shop' => NULL, 'thumb' => NULL),
      'template' => 'fm_commerce_emails_store_order_confirmation'
     ),
     'fm_commerce_emails_admin_order_confirmation' => array(
	    'variables' => array('order' => NULL,  'product' => NULL, 'shop' => NULL, 'thumb' => NULL),
      'template' => 'fm_commerce_emails_admin_order_confirmation'
     ),
    'fm_commerce_emails_store_order_shipped' => array(
	    'variables' => array('order' => NULL,  'product' => NULL, 'shop' => NULL, 'thumb' => NULL),
      'template' => 'fm_commerce_emails_store_order_shipped'
     ),
    'fm_commerce_emails_user_order_shipped' => array(
	    'variables' => array('order' => NULL,  'product' => NULL, 'shop' => NULL, 'thumb' => NULL),
      'template' => 'fm_commerce_emails_user_order_shipped'
     ),
    'fm_commerce_emails_admin_order_shipped' => array(
	    'variables' => array('order' => NULL,  'product' => NULL, 'shop' => NULL, 'thumb' => NULL),
      'template' => 'fm_commerce_emails_admin_order_shipped'
     ),
    'fm_commerce_emails_designer_order_vendor_paid' => array(
	    'variables' => array('order' => NULL,  'product' => NULL, 'shop' => NULL, 'thumb' => NULL),
      'template' => 'fm_commerce_emails_designer_order_vendor_paid'
     ),
     
     'fm_commerce_emails_designer_order_reminder_to_ship' => array(
	    'variables' => array('order' => NULL,  'product' => NULL, 'shop' => NULL, 'thumb' => NULL),
      'template' => 'fm_commerce_emails_designer_order_reminder_to_ship'
     ),
     
     
    'fm_commerce_emails_admin_order_authorized' => array(
	    'variables' => array('order' => NULL,  'product' => NULL, 'shop' => NULL, 'thumb' => NULL),
      'template' => 'fm_commerce_emails_admin_order_authorized'
     ),
	);
}

function fm_commerce_emails_send_order_notifications($updated_status, $order) {
	
	switch($updated_status) {
		case 'fm_orders_captured':
			fm_commerce_emails_captured($order);
			break;
		default:
			break;
	}

}

function fm_commerce_emails_captured($order) {
  global $user;
	$product = fm_commerce_get_order_product($order);
	$shop = fm_commerce_get_store($product);
	$store_owner = fm_commerce_store_owners_get_user($shop);
	
	$test = theme('fm_commerce_emails_user_order_confirmation', 
	                         array('order' => $order, 'product' => $product, 'shop' => $shop, 'thumb' => '') );

	var_dump($test);
	
	$email = variable_get('site_mail', 'admin@fadmashion.com');
	 
	//send to user
	$params = array(
	  'order' => $order, 'product' => $product,  'shop' => $shop
  );
  drupal_mail(
      'fm_commerce_emails',
      'fm_commerce_emails_user_order_confirmation',
      $user->mail,
      language_default(),
      $params,
      'Fadmashion <' . $email . '> '
    );
  
  //send to designer
  drupal_mail(
      'fm_commerce_emails',
      'fm_commerce_emails_store_order_confirmation',
      $store_owner->mail,
      language_default(),
      $params,
      'Fadmashion <' . $email . '> '
   ); 
    
  drupal_mail(
      'fm_commerce_emails',
      'fm_commerce_emails_admin_order_confirmation',
      'misternyce@gmail.com', //$email,
      language_default(),
      $params,
      'Fadmashion Orders <' . $email . '> '
   );  
}


/**
 * Implements hook_mail().
 */
function fm_commerce_emails_mail($key, &$message, $params) {
	$message['module'] = 'fm_commerce_emails';
	$message['key'] = $key;
	
	$order = $params['order'];
	$product = $params['product'];
	$shop = $params['shop'];
	
	$image = fm_commerce_product_image_thumb($product, 'fm_product_confirm', array('style' => "border: 1px solid #e2dcd6; width: 142px;"));
	
	if($key == 'fm_commerce_emails_user_order_confirmation') {
	
	  $message['subject'] =  'Order #' . $order->order_id . ': ' . $product->title . ' by ' . $shop->name;
	  $message['body'] = theme('fm_commerce_emails_user_order_confirmation', 
	                         array('order' => $order, 'product' => $product, 'shop' => $shop, 'thumb' => $image) );
	
	} else if($key == 'fm_commerce_emails_store_order_confirmation') {
		
		$message['subject'] = 'Customer Ordered ' . $product->title . ' on Fadmashion.com (#' . $order->order_id . ')';
	  $message['body'] = theme('fm_commerce_emails_store_order_confirmation', 
	                         array('order' => $order, 'product' => $product, 'shop' => $shop, 'thumb' => $image) );
	} 
  else if($key == 'fm_commerce_emails_admin_order_confirmation') {
		
		$message['subject'] =  fm_users_fullname() .  ' Ordered (#' . $order->order_id . ') ' . $product->title . ' by ' . $shop->name . ' (#' . $order->order_id . ')';
	  $message['body'] = theme('fm_commerce_emails_admin_order_confirmation', 
	                         array('order' => $order, 'product' => $product, 'shop' => $shop, 'thumb' => $image) );
	}
	
	var_dump($message['body']);
	exit();
	
  return $message;
}
