<?php


/**
 * Implements hook_schema().
 */
function fm_commerce_store_schema() {
  $schema = array();

  $schema['fm_commerce_store'] = array(
    'description' => "Base table for the fm_commerce_store entity.",
    'fields' => array(
      'store_id' => array(
        'description' => 'The primary identifier of a store.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
    )
  );
  return $schema;
}

